### ISSUE TITLE
Can't copy words

### ISSUE THREAD

**Issue by idwangmo** [Leopoldthecoder/doctor-jones-extension#5]
When I use Docotr-jones-extension to format our web page, the first copy was cancelled, the second copy was successful. When I closed the extension, thier was normal. And I use manual mode, this problem does not occur.

**Comment by Leopoldthecoder** [comment]
Could you tell me the url of the web page?

I guess this is because when you were trying to copy a selection, the page's content changed, which leads to a replacement of text nodes initiated by the extension.

**Comment by idwangmo** [comment]
All pages, including current page 😂.  I guess the reason is chrome extension conflict, because I can't reproducing in incognito mode.

**Comment by Leopoldthecoder** [comment]
When a text node does not contain at least one Chinese character, Doctor Jones will skip it, so the replacement won't happen.

If the current page, which has no Chinese character, reproduces the issue, you're probably right about extension conflict.

Any guess which extension causes the conflict?

**Comment by leung44** [comment]
+1，插件开启后左键的选中功能变得很奇怪，双击也很难选中字块，望修复

**Comment by Leopoldthecoder** [comment]
@leung44 https://github.com/Leopoldthecoder/doctor-jones-extension/commit/738efa3cf6361e00573c8575124435b8ea63a22f 已经修复这个问题，目前在等谷歌审核。

**Comment by Leopoldthecoder** [comment]
1.1.0 已发布。
