### ISSUE TITLE
希望对英文的适配做得更好一点

### ISSUE THREAD

**Issue by leung44** [Leopoldthecoder/doctor-jones-extension#6]
![Snipaste_2019-10-08_10-25-42](https://user-images.githubusercontent.com/30283855/66362633-296f7200-e9b6-11e9-95e4-34f0298d8af4.png)

**Comment by Leopoldthecoder** [comment]
你好，原文是怎样的？具体是指哪里的适配？

**Comment by leung44** [comment]
> 你好，原文是怎样的？具体是指哪里的适配？

抱歉抱歉 , 就是我看到 " isn't " 里的空格有点奇怪 , 不过好像不是 doctor-jones 的问题 😂

**Comment by Leopoldthecoder** [comment]
好的，有问题的话再反馈
